DELETE FROM customers;
ALTER TABLE customers MODIFY ("ID" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 1);
insert into customers ("NAME", "BIRTH_DATE", "DOCUMENT_ID", "EMAIL") 
values ('Teste', TO_DATE('1995/05/17','YYYY/MM/dd'), 123452789, 'ronald.liboni@acad.pucrs.br'); 